### ISSUE TITLE
TfTransformer::lookupTransform doesnot have return value

### ISSUE THREAD

**Issue by RigerLee** [ethz-asl/voxgraph#27]
Thank you for your great work! 
I've run this code using my own data and found a small problem [here](https://github.com/ethz-asl/voxgraph/blob/master/voxgraph/src/frontend/map_tracker/transformers/tf_transformer.cpp). I believe TfTransformer::lookupTransform should return true at the end of this function.

**Comment by victorreijgwart** [comment]
Thank you!
Yes, you're right. We have a PR open that would fix this issue [here](https://github.com/ethz-asl/voxgraph/pull/16#discussion_r411679989) - but it might take a few more days until it's merged.
If you prefer you could also open a separate PR to fix this issue, then we could merge the fix right away.

**Comment by RigerLee** [comment]
Ok, just use this issue to remind newcomers like me before your merge :)

**Comment by victorreijgwart** [comment]
@RigerLee PR #16 is now merged :)
