### ISSUE TITLE
Error with arche_demo

### ISSUE THREAD

**Issue by pcarrascof** [ethz-asl/voxgraph#46]
Always appear:

[ WARN] [1606720602.223973126, 1562071195.639770510]: Lookup would require extrapolation at time 1562071185.811160832, but only time 1562071181.793263616 is in the buffer, when looking up transform from frame [os1_lidar] to frame [odom]

**Comment by victorreijgwart** [comment]
Does the warning appear a few times at the start of the rosbag, or constantly?

**Comment by pcarrascof** [comment]
Constantly, during all rosbag.

**Comment by victorreijgwart** [comment]
Are you running the exact arche_demo launch file, or did you make modifications?
What operating system release and CPU are you using? Are you running it off an SSD?

**Comment by pcarrascof** [comment]
I am booting as stated in the wiki with roslaunch voxgraph arche_demo.launch with my rosbag_path without any modification in the code. I am running Ros Melodic on Ubuntu 18.04, with i7-9750H CPU.

**Comment by alexmillane** [comment]
Is the dataset coming off a Solid State Drive (SSD)?

@victorreijgwart Does this indicate that the pointcloud is arriving **before** the pose from Rovio?

**Comment by pcarrascof** [comment]
I downloaded the bag file on my own computer. I have Ubuntu installed on the main SSD of the computer, but I don't think that's it. At first I thought that the "--clock" was missing to start the rosbag but it is contemplated so I can't find the error.

**Comment by victorreijgwart** [comment]
The CPU you're using should definitely be fast enough, and Ubuntu 18.04 is the same as what we're running. So everything looks good there. Also good you're running it off an SSD.

@alexmillane yes it seems like the pointclouds arrive before the TFs are updated. This is quite odd, I've only seen the opposite happen before. The chain from `os1_lidar` to `odom` also contains a static TF publisher (launched [here](https://github.com/ethz-asl/voxgraph/blob/master/voxgraph/launch/arche_demo.launch#L11)), in addition to the TF from ROVIO which comes from the rosbag. This has caused issues in the past when `use_sim_time: true` was not being read, but if this was the case the time mismatch should be much larger.

@pcarrascof, could you share a screenshot of your TF tree (for example using [rqt](http://wiki.ros.org/rqt_tf_tree)) with us? It should look like the one here: https://github.com/ethz-asl/voxgraph/issues/32#issuecomment-659698337

**Comment by victorreijgwart** [comment]
@pcarrascof, is it working for you now? If it is, or if you are no longer looking for a solution, feel free to close this GitHub issue.
