### ISSUE TITLE
Build errors in Noetic

### ISSUE THREAD

**Issue by droter** [ethz-asl/voxgraph#47]
I updated the CMakeLists.txt to use:
-std=c++14

I am getting this error when building:
/root/src/voxgraph/voxgraph/src/frontend/submap_collection/voxgraph_submap.cpp: In member function ‘const voxgraph::WeightedSampler<voxgraph::RegistrationPoint>& voxgraph::VoxgraphSubmap::getRegistrationPoints(voxgraph::VoxgraphSubmap::RegistrationPointType) const’:
/root/src/voxgraph/voxgraph/src/frontend/submap_collection/voxgraph_submap.cpp:141:1: error: control reaches end of non-void function [-Werror=return-type]
  141 | }
      | ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/voxgraph.dir/build.make:154: CMakeFiles/voxgraph.dir/src/frontend/submap_collection/voxgraph_submap.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:3253: CMakeFiles/voxgraph.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Any ideas?

**Comment by victorreijgwart** [comment]
Hi @droter,

Does the error disappear when adding a default clause to the switch statement in the [`VoxgraphSubmap::getRegistrationPoints(...)`](https://github.com/ethz-asl/voxgraph/blob/master/voxgraph/src/frontend/submap_collection/voxgraph_submap.cpp#L131) method? E.g.
```
  switch (registration_point_type) {
    case RegistrationPointType::kVoxels:
      return relevant_voxels_;
    case RegistrationPointType::kIsosurfacePoints:
    default:
      return isosurface_vertices_;
  }
```

**Comment by droter** [comment]
I was able to get it to build inside of this docker container.  I might not have the right setup locally.

https://github.com/koide3/voxgraph/

**Comment by LXYYY** [comment]
@droter ,I think you can check your compiler you are using, If you are using some compiler like clang, it has stricter syntax rules. If you switch to gcc, these errors should be gone
