### ISSUE TITLE
tf error

### ISSUE THREAD

**Issue by Rogers34** [ethz-asl/voxgraph#48]
Dear friend!
    I follow the command in the README.md and download the demo dataset. Then i run the demo, something wrong displayed.
Could you give me some advice, help me to find out what is the problem? Thanks a lot!

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

rogers@rogers-GL65-9SD:~/nowhere/catkin_build_ws$ roslaunch voxgraph arche_demo.launch 
... logging to /home/rogers/.ros/log/7135fcc2-4e77-11eb-9ed0-00d86186c0ec/roslaunch-rogers-GL65-9SD-18335.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rogers-GL65-9SD:45995/

SUMMARY
========

PARAMETERS
 * /lidar_undistortion/lidar_frame_id: os1_lidar
 * /lidar_undistortion/odom_frame_id: odom
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /use_sim_time: True
 * /voxgraph_mapper/auto_pause_rosbag: False
 * /voxgraph_mapper/debug: True
 * /voxgraph_mapper/input_base_link_frame: imu
 * /voxgraph_mapper/input_odom_frame: odom
 * /voxgraph_mapper/measurements/height/enabled: False
 * /voxgraph_mapper/measurements/height/information_zz: 2500.0
 * /voxgraph_mapper/measurements/odometry/enabled: True
 * /voxgraph_mapper/measurements/odometry/information_matrix/x_x: 1.0
 * /voxgraph_mapper/measurements/odometry/information_matrix/y_y: 1.0
 * /voxgraph_mapper/measurements/odometry/information_matrix/yaw_yaw: 2500.0
 * /voxgraph_mapper/measurements/odometry/information_matrix/z_z: 2500.0
 * /voxgraph_mapper/measurements/submap_registration/enabled: True
 * /voxgraph_mapper/measurements/submap_registration/information_matrix/x_x: 1.0
 * /voxgraph_mapper/measurements/submap_registration/information_matrix/y_y: 1.0
 * /voxgraph_mapper/measurements/submap_registration/information_matrix/yaw_yaw: 1.0
 * /voxgraph_mapper/measurements/submap_registration/information_matrix/z_z: 1.0
 * /voxgraph_mapper/measurements/submap_registration/registration_method: explicit_to_implicit
 * /voxgraph_mapper/measurements/submap_registration/sampling_ratio: 0.05
 * /voxgraph_mapper/mesh_min_weight: 2.0
 * /voxgraph_mapper/mesh_use_color: False
 * /voxgraph_mapper/output_base_link_frame: imu
 * /voxgraph_mapper/output_mission_frame: mission
 * /voxgraph_mapper/output_odom_frame: odom
 * /voxgraph_mapper/output_sensor_frame: sensor_voxgraph
 * /voxgraph_mapper/pointcloud_topic: lidar_undistortio...
 * /voxgraph_mapper/submap_creation_interval: 10
 * /voxgraph_mapper/subscriber_queue_length: 10
 * /voxgraph_mapper/tsdf_integrator/max_ray_length_m: 16.0
 * /voxgraph_mapper/tsdf_integrator/sparsity_compensation_factor: 20.0
 * /voxgraph_mapper/tsdf_integrator/truncation_distance: 0.6
 * /voxgraph_mapper/tsdf_integrator/use_const_weight: True
 * /voxgraph_mapper/tsdf_integrator/use_sparsity_compensation_factor: True
 * /voxgraph_mapper/tsdf_integrator/use_weight_dropoff: True
 * /voxgraph_mapper/tsdf_voxel_size: 0.2
 * /voxgraph_mapper/verbose: False

NODES
  /
    lidar_undistortion (lidar_undistortion/lidar_undistortion_node)
    os1_stuff (tf/static_transform_publisher)
    player (rosbag/play)
    rviz_rogers_GL65_9SD_18335_2592713585378453169 (rviz/rviz)
    voxgraph_mapper (voxgraph/voxgraph_mapping_node)

auto-starting new master
process[master]: started with pid [18345]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7135fcc2-4e77-11eb-9ed0-00d86186c0ec
process[rosout-1]: started with pid [18356]
started core service [/rosout]
process[os1_stuff-2]: started with pid [18363]
process[lidar_undistortion-3]: started with pid [18364]
process[player-4]: started with pid [18369]
process[voxgraph_mapper-5]: started with pid [18376]
[ INFO] [1609756047.903474921]: Opening /home/rogers/nowhere/voxgraph-data/arche_flight1_2ms_indoor-outdoor-figure-8.bag
process[rviz_rogers_GL65_9SD_18335_2592713585378453169-6]: started with pid [18383]
[ INFO] [1609756047.929197677]: Using transform from pointcloud sensor to robot base link from TFs
[ INFO] [1609756047.998748872]: rviz version 1.13.15
[ INFO] [1609756047.998793812]: compiled against Qt version 5.9.5
[ INFO] [1609756047.998804592]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1609756048.003008598]: Forcing OpenGl version 0.
Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
[ INFO] [1609756048.363605706, 1562071179.318499904]: Stereo is NOT SUPPORTED
[ INFO] [1609756048.363656027, 1562071179.318499904]: OpenGl version: 4.6 (GLSL 4.6).
[ WARN] [1609756048.600736036, 1562071179.560158115]: Waited 0.250s, but still could not get the TF from os1_lidar to odom
[ WARN] [1609756048.601356375, 1562071179.560158115]: Could not get correction transform within allotted time. Skipping pointcloud.
[ WARN] [1609756048.860881714, 1562071179.812397871]: Waited 0.250s, but still could not get the TF from os1_lidar to odom
[ WARN] [1609756048.860964850, 1562071179.812397871]: Could not get correction transform within allotted time. Skipping pointcloud.
[ WARN] [1609756049.142510948, 1562071180.095394429]: Waited 0.250s, but still could not get the TF from os1_lidar to odom
[ WARN] [1609756049.142609145, 1562071180.095394429]: Could not get correction transform within allotted time. Skipping pointcloud.
[ WARN] [1609756049.177964208, 1562071180.135786926]: Lookup would require extrapolation into the past.  Requested time 1562071179.496815616 but the earliest data is at time 1562071179.498913499, when looking up transform from frame [os1_lidar] to frame [odom]
[ INFO] [1609756049.308728131, 1562071180.266818730]: Created submap: 0 with pose
0.722252  0.69163        0  25.6613
-0.69163 0.722252       -0   5.9009
      -0        0        1  1.40414
       0        0        0        1
[ INFO] [1609756049.308768162, 1562071180.266818730]: Setting pose of submap 0 to constant
[ INFO] [1609756049.308947256, 1562071180.266818730]: Optimizing the pose graph

Solver Summary (v 1.14.0-eigen-(3.3.7)-lapack-suitesparse-(4.2.1)-cxsparse-(3.1.2)-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                            0                        0
Parameters                                  0                        0
Residual blocks                             0                        0
Residuals                                   0                        0

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                    SPARSE_SCHUR   SPARSE_NORMAL_CHOLESKY
Threads                                     4                        4
Linear solver ordering              AUTOMATIC                AUTOMATIC

Cost:
Initial                          0.000000e+00
Final                            0.000000e+00
Change                           0.000000e+00

Minimizer iterations                       -2
Successful steps                           -1
Unsuccessful steps                         -1

Time (in seconds):
Preprocessor                         0.000570

  Residual only evaluation          -1.000000 (-1)
  Jacobian & residual evaluation    -1.000000 (-1)
  Linear solver                     -1.000000 (-1)
Minimizer                            0.000009

Postprocessor                        0.000001
Total                                0.000579

Termination:                      CONVERGENCE (Function tolerance reached. No non-constant parameter blocks found.)

[ INFO] [1609756049.390059431, 1562071180.347388613]: Initialized TSDF Integrator
[ WARN] [1609756068.986600028, 1562071199.942990429]: Waited 0.260s, but still could not get the TF from os1_lidar to imu
[ WARN] [1609756068.986635043, 1562071199.942990429]: Skipping pointcloud since the poses at time 1562071189.694679808 could not be looked up.
[ WARN] [1609756069.248504907, 1562071200.205136054]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756069.248531199, 1562071200.205136054]: Skipping pointcloud since the poses at time 1562071189.894714880 could not be looked up.
[ WARN] [1609756069.510160998, 1562071200.467219255]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756069.510193049, 1562071200.467219255]: Skipping pointcloud since the poses at time 1562071190.094666240 could not be looked up.
[ WARN] [1609756069.771911866, 1562071200.729230927]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756069.771939513, 1562071200.729230927]: Skipping pointcloud since the poses at time 1562071190.394607616 could not be looked up.
[ WARN] [1609756070.033524237, 1562071200.991063868]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756070.033551682, 1562071200.991063868]: Skipping pointcloud since the poses at time 1562071190.594625280 could not be looked up.
[ WARN] [1609756070.295076839, 1562071201.253106251]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756070.295104439, 1562071201.253106251]: Skipping pointcloud since the poses at time 1562071190.794618880 could not be looked up.
[ WARN] [1609756070.556756404, 1562071201.515049288]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756070.556783001, 1562071201.515049288]: Skipping pointcloud since the poses at time 1562071190.994553344 could not be looked up.
[ WARN] [1609756070.818293062, 1562071201.777059135]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756070.818320336, 1562071201.777059135]: Skipping pointcloud since the poses at time 1562071191.194543360 could not be looked up.
[ WARN] [1609756071.079907970, 1562071202.039037192]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756071.079936164, 1562071202.039037192]: Skipping pointcloud since the poses at time 1562071191.394503936 could not be looked up.
[ WARN] [1609756071.341590984, 1562071202.301023435]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756071.341618616, 1562071202.301023435]: Skipping pointcloud since the poses at time 1562071191.694452480 could not be looked up.
[ WARN] [1609756071.603026144, 1562071202.563084601]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756071.603052350, 1562071202.563084601]: Skipping pointcloud since the poses at time 1562071191.894448128 could not be looked up.
[ WARN] [1609756071.864625016, 1562071202.825047589]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756071.864652971, 1562071202.825047589]: Skipping pointcloud since the poses at time 1562071192.094497024 could not be looked up.
[ WARN] [1609756072.126236708, 1562071203.086878579]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756072.126264524, 1562071203.086878579]: Skipping pointcloud since the poses at time 1562071192.294529536 could not be looked up.
[ WARN] [1609756072.387749007, 1562071203.348820838]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756072.387780214, 1562071203.348820838]: Skipping pointcloud since the poses at time 1562071192.494533632 could not be looked up.
[ WARN] [1609756072.649380202, 1562071203.604739603]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756072.649415921, 1562071203.604739603]: Skipping pointcloud since the poses at time 1562071192.695714304 could not be looked up.
[ WARN] [1609756072.910954616, 1562071203.866884881]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756072.910980228, 1562071203.866884881]: Skipping pointcloud since the poses at time 1562071192.995470592 could not be looked up.
[ WARN] [1609756073.172560120, 1562071204.129634823]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756073.172593121, 1562071204.129634823]: Skipping pointcloud since the poses at time 1562071193.194676992 could not be looked up.
[ WARN] [1609756073.434118213, 1562071204.394529467]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756073.434144173, 1562071204.394529467]: Skipping pointcloud since the poses at time 1562071193.393713664 could not be looked up.
[ WARN] [1609756073.695666159, 1562071204.656663741]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756073.695691669, 1562071204.656663741]: Skipping pointcloud since the poses at time 1562071193.593147904 could not be looked up.
[ WARN] [1609756073.887548857, 1562071204.848113671]: Lookup would require extrapolation into the future.  Requested time 1562071195.027399680 but the latest data is at time 1562071189.494492160, when looking up transform from frame [os1_lidar] to frame [odom]
[ WARN] [1609756073.957157394, 1562071204.918646986]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756073.957229511, 1562071204.918646986]: Skipping pointcloud since the poses at time 1562071193.795046912 could not be looked up.
[ WARN] [1609756074.218731545, 1562071205.171418133]: Waited 0.260s, but still could not get the TF from imu to odom
[ WARN] [1609756074.218758592, 1562071205.171418133]: Skipping pointcloud since the poses at time 1562071193.995794176 could not be looked up.
^C[ WARN] [1609756074.289965705, 1562071205.242170174]: Lookup would require extrapolation into the future.  Requested time 1562071195.423395328 but the latest data is at time 1562071189.494492160, when looking up transform from frame [os1_lidar] to frame [odom]
[rviz_rogers_GL65_9SD_18335_2592713585378453169-6] killing on exit
[voxgraph_mapper-5] killing on exit
[player-4] killing on exit
[lidar_undistortion-3] killing on exit
[os1_stuff-2] killing on exit
^C
^C^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by victorreijgwart** [comment]
Hi @Rogers34, could you share some details about the hardware and OS you're running voxgraph on?
