### ISSUE TITLE
RGBD dataset and depth extract

### ISSUE THREAD

**Issue by glennliu** [ethz-asl/voxgraph#53]
Hi 

May I know where to find this dataset used in the paper?
It looks like the machine hall dataset, which does not have depth provided. How do you create depth images to voxgraph?

Thanks

![Screenshot from 2021-02-02 21-46-48](https://user-images.githubusercontent.com/8009679/106609252-59c22300-65a0-11eb-9c30-b83322b36b91.png)

**Comment by glennliu** [comment]
Found the image_undisort node. Closing the issue.

**Comment by alexmillane** [comment]
@glennliu This is a different dataset to the Euroc Machine Hall dataset. Here we actually flew with an rgb-d camera. 

I'm working on uploading the datasets now (on quite a slow internet connection).

**Comment by glennliu** [comment]
> @glennliu This is a different dataset to the Euroc Machine Hall dataset. Here we actually flew with an rgb-d camera.
> 
> I'm working on uploading the datasets now (on quite a slow internet connection).

Thanks for letting me know.
Where can I access to the dataset when you finish uploading?

**Comment by alexmillane** [comment]
@glennliu Please email me: alex.millane@gmail.com
