### ISSUE TITLE
About feature/multi-robot

### ISSUE THREAD

**Issue by LXYYY** [ethz-asl/voxgraph#59]
Hi Victor, I noticed that multi-robot branch, I was doing similar work last months. I wanted to try this branch, but I can't find a match voxblox branch. Have you committed yet? and how much has been done so far, is it workable now?

**Comment by LXYYY** [comment]
I found the multi robot branch in voxblox, somehow missed it yesterday

**Comment by victorreijgwart** [comment]
Hi @LXYYY, yes the feature/multi-robot branch on voxgraph is compatible with the similarly named voxblox branch. As you might have seen, the changes so far are quite small though. It mainly makes it possible to receive and include submaps from other robots, while correctly setting their odometry constraints. The more exciting puzzle pieces like detecting loop closures between different robots and distributed optimization are still missing.
