### ISSUE TITLE
lidar_odometry and coloring_point

### ISSUE THREAD

**Issue by bulinx** [ethz-asl/voxgraph#61]
I'm sorry to ask this seemingly simple question. But I haven't found a solution for a long time.
I have installed voxgraph and run the packages then have a good result, when I use my own packages there have many problems（my platforms: ubuntu18 melodic), I want to realized coloring lidar point to creat dense map. 

1 : I change the odometry source to hdl-graph-slam, my hdl tf tree :
![image](https://user-images.githubusercontent.com/52736133/119633967-d5dcc100-be44-11eb-9466-155a610bf998.png)
there I change the **voxgraph_mapper.yaml** to :

- input_odom_frame: odom
- input_base_link_frame: base_link
- output_mission_frame: mission
- output_odom_frame: odom
- output_base_link_frame: base_link
- output_sensor_frame: sensor_voxgraph

2: I change the source of dense (depth) data to my coloring-lidarpoint（In fact, it is the color point obtained by the projection between the lidar and the camera）

there I change the **pointcloud_topic** to **/pcl_coloring/velodyne_coloured**

my launch flies : 
![image](https://user-images.githubusercontent.com/52736133/119655003-a6857e80-be5b-11eb-8ffb-b11f94fe4f6c.png)

My steps : 
> roslaunch hdl-graph-slam  my.launch     -----for lidar odometry

> roslaunch coloring my.launch             -----for coloring depth data

> roslaunch voxgraph my.launch rosbag path ：= /my.bag      ----run voxgraph

Final running result：
![image](https://user-images.githubusercontent.com/52736133/119635821-a16a0480-be46-11eb-80d2-baaa162fddb7.png)

**my odometry and depth data all failed to input.**

So I don't know how to run your code correctly with my package. Can you provide some solutions? Thank you very much.

**Comment by victorreijgwart** [comment]
From the TF tree it looks like the timestamps of `velodyne_nodelet_manager` are 1744584 seconds behind the rest of the system. Are you running voxgraph on a live robot, from a rosbag or in simulation? If you're running it from rosbag or in simulation, you should set the `use_sim_time` param to `true` before launching the rest of your system. If you're running it from a rosbag, you should also set the `--clock` param.

**Comment by bulinx** [comment]
> From the TF tree it looks like the timestamps of `velodyne_nodelet_manager` are 1744584 seconds behind the rest of the system. Are you running voxgraph on a live robot, from a rosbag or in simulation?
> If you're running it from rosbag or in simulation, you should set the `use_sim_time` param to `true` before launching the other nodes. If you're running it from a rosbag, you should also supply it with the `--clock` argument.

Sorry, I’ve updated the question again, I running voxgraph with my rosbag which Information collection performed by VLP-16, mono, and imu of my own robot.  I will try your suggestion again.  But I still have some  questions above, apologies for the lengthy message and hope my questions are well defined!

**Comment by victorreijgwart** [comment]
In the rqt graph you shared, the pointcloud topic is not being subscribed to by voxgraph.
Could you remove/disable the `lidar_undistortion` node in voxgraph's launch file, directly map the pointcloud topic to voxgraph itself, and let me know if the map then shows something?

**Comment by victorreijgwart** [comment]
Actually, when looking at it again, the rqt graph is inconsistent with your launch file screenshot. Are you sure you're launching your new launch file?
