### ISSUE TITLE
Large delay in pose graph update

### ISSUE THREAD

**Issue by KirillMouraviev** [ethz-asl/voxgraph#70]
Hello,
I ran arche_demo on a PC with Intel i5 6-core processor and 32 GB RAM. I noticed large delay in submap integration and pose graph update. After approximately 1 min of running, only 3 submaps near start position were created:
![submaps_on_1min](https://user-images.githubusercontent.com/15195368/174036478-08b8e80d-b746-4a6a-b4c7-2c59fc99abac.png)

After full rosbag (6 min) has passed, about 1/3 of whole path were integrated into pose graph:
![mesh_on_5min](https://user-images.githubusercontent.com/15195368/174036774-9819275f-c759-4603-8fdb-a6098f3cda96.png)
![mesh_full2](https://user-images.githubusercontent.com/15195368/174036735-e6642684-3e72-44fd-afe2-d4956c29a013.png)

According to console log, creation of one submap took about 50 seconds. The most time-consuming operations were ESDF generation (21 sec), layer transformation (20 sec), and search of isosurface voxels (6 sec).
![console_submaps_edited](https://user-images.githubusercontent.com/15195368/174037048-35a9af61-5ff0-4966-ac1d-2c4b04c291f5.png)

CPU load remained near to full (600%) during all time of the experiment.
![htop](https://user-images.githubusercontent.com/15195368/174038150-0895a793-5546-4426-b1f2-48a8183958b1.png)

I used voxblox to create submaps. I ran the experiment via the following command:
`roslaunch voxgraph arche_demo.launch rosbag_path:=${HOME}/Downloads/arche_flight1_2ms_indoor-outdoor-figure-8.bag`
Here is my voxgraph package with all configs: 
[voxgraph.zip](https://github.com/ethz-asl/voxgraph/files/8917538/voxgraph.zip)

Is this normal behaviour? And is it possible to make submap integration faster?

**Comment by sam-thomas-dd** [comment]
Is your bag file compressed? I found that decompressing the cow and lady dataset was crucial to real time performance.

**Comment by KirillMouraviev** [comment]
No, bag file is not compressed. I also ran experiments in simulation with RGBD camera model, and update delays were also very large.

**Comment by KirillMouraviev** [comment]
I have noticed that each submap requires more time for creation than previous one. It seems that temporal window in Voxblox does not work, and each submap includes all data from start of the algorithm.

**Comment by KirillMouraviev** [comment]
The reason was in the method choice in `voxblox_temporal_window.yaml` config file. I chose `fast` method, but pointcloud deintegration works only with `projective` method.
